// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlVazdKwILJvb48RXRtCHBXW39JI5LXyY',
    appId: '1:129694048718:web:9e6e0f2fcc90800aa64b9f',
    messagingSenderId: '129694048718',
    projectId: 'besheger-apps',
    authDomain: 'besheger-apps.firebaseapp.com',
    storageBucket: 'besheger-apps.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcm1Orw41Ls9OV6HHgj6QupkT7vQ2dKtQ',
    appId: '1:129694048718:android:600a288898139692a64b9f',
    messagingSenderId: '129694048718',
    projectId: 'besheger-apps',
    storageBucket: 'besheger-apps.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALouBWqKmp_neWcN2zhyzd86Tx61EctIs',
    appId: '1:129694048718:ios:a14b2c6f583cb5b1a64b9f',
    messagingSenderId: '129694048718',
    projectId: 'besheger-apps',
    storageBucket: 'besheger-apps.appspot.com',
    iosBundleId: 'com.besheger.learn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALouBWqKmp_neWcN2zhyzd86Tx61EctIs',
    appId: '1:129694048718:ios:8f0b260416d4bf04a64b9f',
    messagingSenderId: '129694048718',
    projectId: 'besheger-apps',
    storageBucket: 'besheger-apps.appspot.com',
    iosBundleId: 'com.besheger.learn.RunnerTests',
  );
}
